@MwSolucoesApi_HostAddress = https://localhost:7259
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYTVkOTI0Yi1lMGZmLTQ5MGYtOTQ5Zi1lY2ExZjczNTVmODkiLCJuYW1laWQiOiJjYTVkOTI0Yi1lMGZmLTQ5MGYtOTQ5Zi1lY2ExZjczNTVmODkiLCJ1bmlxdWVfbmFtZSI6Ik1hdGhldXMgV2lsbGlhbiIsInJvbGUiOiJDbGllbnRlIiwiYWNjZXNzX2xldmVsIjoiQ29tdW0iLCJqdGkiOiI2MmM1YTUyMi1jMjFkLTRmMTMtYjkyMS03YWU1Nzg4ODBiMTQiLCJpYXQiOjE3ODI3ODg3MzMsIm5iZiI6MTc4Mjc4ODczMywiZXhwIjoxNzgyNzkyMzMzLCJpc3MiOiJNd1NvbHVjb2VzLkFwaSIsImF1ZCI6Ik13U29sdWNvZXMuQ2xpZW50In0.HcSTFvuaGUdzjufMsC--aXqzK4ITdg-9O5TAmIp6lpQ

GET {{MwSolucoesApi_HostAddress}}/api/testconnection/check
Accept: application/json

###

POST {{MwSolucoesApi_HostAddress}}/api/user
Accept: application/json
Content-Type: application/json
{
  "Name": "Matheus Willian do Nascimento",
  "Email": "matheus@dxc.com",
  "PhoneNumber" : "11999999991",
  "Cpf": "53056582415",
  "Password": "12345678",
  "ConfirmPassword": "12345678",
  "Logradouro": "Rua Teste",
  "Numero": "123",
  "Cep": "57040530",
  "Bairro": "Bairro Teste",
  "Cidade": "Cidade Teste",
  "Estado": "AL"
}
###

POST {{MwSolucoesApi_HostAddress}}/api/auth/login 
Accept: application/json
Content-Type: application/json
{
  "Email":"matheus.willian@dxc.com",
  "Password":"12345678"
}

###

GET {{MwSolucoesApi_HostAddress}}/api/user/me
Accept: application/json
Authorization: Bearer {{token}}

###

PUT {{MwSolucoesApi_HostAddress}}/api/user/me
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "Matheus Willian",
  "Email": "matheus.willian@dxc.com",
  "PhoneNumber" : "11999999299",
  "Cpf": "53056582415",
  "Password": "12345678",
  "ConfirmPassword": "12345678",
  "Logradouro": "Rua Teste",
  "Numero": "12",
  "Cep": "57040530",
  "Bairro": "Bairro Teste",
  "Cidade": "Cidade Teste",
  "Estado": "AL"
}
###